---
version: '2'
volumes:
  share:
services:
  django:
    build: ./django
    image: django-img
    hostname: django
    container_name: django
    memswap_limit: 0
    mem_limit: 512000000
    volumes:
      - "share:/opt/swapi"
    ports:
      - "8000:8000"
